name: Deploy to DEV CV Cluster
env:
  AWS_DEFAULT_REGION: us-west-2
  AWS_ECR: 130290943060.dkr.ecr.us-west-2.amazonaws.com
  DISABLE_DB_SYNCHRONIZE: true
  GITHUB_ACCESS_TOKEN: ${{ secrets.SHARED_PACKAGES_READ }}
  GIT_SHA: ${{ github.event.pull_request.head.sha || github.event.push.head.sha }}
  LATEST_TAG: 'latest'
  TAG: 'latest'
  IMAGE-TAG: 'latest'
  SERVICE_NAME: 'cv-engine-service'
  ENV: ${{ github.event.inputs.env }}  # Initialize with user input

on:
  workflow_run:
    workflows:
      - "CI"
    types:
      - completed
    branches:
      - main
      
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  aws_service_and_Infra_creation_updation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::130290943060:role/gha-actions-assume-role
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
          role-session-name: GhaActionsAwsResourcesCreationUpdation
      - name: Set the folder to monitor changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            app:
              - 'app/**'
            dev:
              - 'deploy/cft-services/dev/**'
              - 'scripts/deploy_to_dev.sh'
              - 'scripts/update_ecs_service.sh'
      - name: Check bucket for the cft-service
        run: |
          chmod +x scripts/services_cft_bucket.sh
          AWS_REGION=${{ env.AWS_DEFAULT_REGION }} ./scripts/services_cft_bucket.sh
      - name: Push file to S3
        if: steps.changes.outputs.dev == 'true'
        run: make upload_to_s3 ENV=dev
      - name: Create/Update the AWS Infra
        if: steps.changes.outputs.dev == 'true'
        run: |
          chmod +x scripts/deploy_to_dev.sh
          ./scripts/deploy_to_dev.sh
      - name: Update ECS service
        if: steps.changes.outputs.app == 'true'
        run: |
          chmod +x scripts/update_ecs_service.sh
          ENV=dev ./scripts/update_ecs_service.sh
      - name: Delete the files in S3 bucket
        run: aws s3 rm s3://hh-cv-services-deployment-bucket/cv-engine-dev --recursive --exclude "*" --include "*.json" --include "*.yml" --include "*.yaml"
